### PR TITLE
Fix derpy searchbox

### PR DESCRIPTION
**Pull request by jk-5**
Screenshots say it all

Before:
screen shot 2015-05-16 at 17 17 47

After:
screen shot 2015-05-16 at 17 17 35

### CODE REVIEW

**Comment by gratimax** [comment]
:+1: Looks good, glad that some people are interested about looking into this sort of thing

**Comment by Tzky** [comment]
searchbox is still derpy for me :/

unbenannt

FF 38.0.1 on Win8.1x64 1080p 100% zoom.

**Comment by jk-5** [comment]
It looks like my change broke it for you. I lifted it up by 1 and made it 1px thicker, which is exactly what's wrong in your screenshot. I tested in chrome and safari. This is an odd cross-browser breaking thing. Thanks for reporting, i will look into it.

**Comment by Tzky** [comment]
It was just 1px shifted to the bottom before.
So you just changed the way it's broken...

**Comment by jk-5** [comment]
Well as i said, in chrome and safari it looks absolutely fine so i should find a better way of fixing it

**Comment by jk-5** [comment]
Okay i identified the issue. Firefox does not respect the `line-height` property. It adds 2 pixels to this value. Chrome doesn't do this.



With this, there is no way to make it look normal without adding browser-specific code

**Comment by gratimax** [comment]
That's what I was worried about :disappointed:, I did try it cross browser but eventually gave up because I thought that I didn't know how best to change the display. It may be a better idea to try to coerce the button into its shape using a different method, or to style the navbar differently.

**Comment by jk-5** [comment]
Give me an hour, then i have time and i'll try to do it in a different way :smile:

**Pull request merged**
